# Load packages
suppressPackageStartupMessages({
  library(shiny, warn.conflicts = FALSE)
  library(bslib, warn.conflicts = FALSE)
  library(DT, warn.conflicts = FALSE)
  library(shinycssloaders, warn.conflicts = FALSE)
  library(shinyBS, warn.conflicts = FALSE)
  library(bsicons, warn.conflicts = FALSE)
  library(httr, warn.conflicts = FALSE)
  library(magrittr, warn.conflicts = FALSE)
  library(readr, warn.conflicts = FALSE)
  library(readxl, warn.conflicts = FALSE)
  library(flextable, warn.conflicts = FALSE)
  library(bayesplot, warn.conflicts = FALSE)
  library(MatrixModels, warn.conflicts = FALSE)
  library(plotly, warn.conflicts = FALSE)
  library(factoextra, warn.conflicts = FALSE)
  library(lme4, warn.conflicts = FALSE)
  library(officer, warn.conflicts = FALSE)
  library(shinyBS, warn.conflicts = FALSE)
  library(gtsummary, warn.conflicts = FALSE)
  library(docstring, warn.conflicts = FALSE)
  library(bayesics, warn.conflicts = FALSE)
  library(dana, warn.conflicts = FALSE)
  library(gt, warn.conflicts = FALSE)
  library(bslib, warn.conflicts = FALSE)
  library(table1, warn.conflicts = FALSE)
  library(bayestestR, warn.conflicts = FALSE)
  library(DiagrammeR, warn.conflicts = FALSE)
})

# Load DANA package
devtools::load_all()