---
title: "get_example_datasets"
author: "Abran Nicolas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

# Load packages

library(MASS)
library(tidyverse)
library(lme4)

set.seed(123)

```


# Cross Sectional

```{r}
# Load Pima data from the MASS package
pima <- MASS::Pima.tr

# Save as CSV
pima %>%
  mutate(type = ifelse(type == "Yes", yes = 1, no = 0)) %>%
  write_csv("pima.csv")

```

# Retrospective Cohort

```{r}
# Load sleepstudy data from the lme4 package
sleepstudy <- lme4::sleepstudy

# Add predictors and outcome variables
sleepstudy <- sleepstudy %>% mutate(Class = sample(x = c("A","B","C"), size = nrow(sleepstudy), replace = TRUE),
                                    ReactionInd = ifelse(Reaction > 250, 1, 0),
                                    ReactionCount = as.integer(Reaction),
                                    Offset = sample(x = seq(1:10), size = nrow(sleepstudy), replace = TRUE))

# Save as CSV
sleepstudy %>%
  write_csv("sleepstudy.csv")

```


```{r}
# Build grouped dataset
x <- rnorm(100)
group <- rep(1:10, each = 10)
intercept <- rep(runif(n = 10, 0, 20), each = 10)
y <- intercept + 2 * x + rnorm(100, 0, 1)

mixed_data <- data.frame(x, group, y)

# Save as CSV
mixed_data %>%
  write_csv("mixed_data1.csv")

```



```{r}

# Build grouped dataset
x <- rnorm(100)
group <- rep(1:10, each = 10)
intercept <- rep(runif(n = 10, 0, 5), each = 10)
y <- exp(intercept + x + rnorm(100, 0, 1))

mixed_data <- data.frame(x, group, y)

# Save as CSV
mixed_data %>%
  write_csv("mixed_data2.csv")

```
